### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by Nutomic**
@calmh Can you enable Travis CI for this repo? I don't have the permissions.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
I enabled it.

**Comment by Nutomic** [comment]
Thanks, didn't know you had the permission. But you were a bit fast with the merge, looks like the build failed.

**Comment by AudriusButkevicius** [comment]
I merged it as I thought travis would not pick it up until its merged

**Comment by Nutomic** [comment]
No it works on any branch of the repo. Anyway I will fix it.

Btw Transifex tells me "Only maintainers are allowed to update the source file". Can you give me permission to update the [syncthing-lite strings](https://www.transifex.com/syncthing/syncthing-lite)?

**Comment by AudriusButkevicius** [comment]
Done

**Pull request merged**
